# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-20 18:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter_app', '0003_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='follow',
            name='status',
            field=models.CharField(default=255, max_length=255),
            preserve_default=False,
        ),
    ]
