# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-23 01:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('twitter_app', '0004_follow_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inbox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_content', models.TextField()),
                ('sender_id', models.IntegerField()),
                ('recipient_id', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='inbox',
            field=models.ForeignKey(default=255, on_delete=django.db.models.deletion.CASCADE, related_name='user_inbox', to='twitter_app.Inbox'),
            preserve_default=False,
        ),
    ]
