# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-23 03:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter_app', '0005_auto_20180423_0143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inbox',
            name='recipient_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='inbox',
            name='sender_id',
            field=models.IntegerField(null=True),
        ),
    ]
